// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateNewUser(ctx context.Context, arg CreateNewUserParams) (sql.Result, error)
	CreateNewUserCredential(ctx context.Context, arg CreateNewUserCredentialParams) (sql.Result, error)
	GetCrendentailByUserId(ctx context.Context, userID int64) (sql.NullString, error)
	GetUserByUsername(ctx context.Context, userName sql.NullString) (int64, error)
}

var _ Querier = (*Queries)(nil)
