CREATE TABLE users (
    id  BIGINT  AUTO_INCREMENT PRIMARY KEY ,
    last_name NVARCHAR(255),
    first_name NVARCHAR(255),
    phone   NVARCHAR(255),
    email   NVARCHAR(255) NOT NULL,
    user_name NVARCHAR(255),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    last_login TIMESTAMP
);

CREATE TABLE credential (
    id BIGINT AUTO_INCREMENT PRIMARY KEY ,
    user_id BIGINT NOT NULL ,
    password_hashed NVARCHAR(1024),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP
);